apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wombat.fullname" . }}-monitored
  labels:
    {{- include "wombat.labels" . | nindent 4 }}
data:
  monitored-environments.yaml: |
    {{- $environments := dict }}
    {{- range $envId, $env := .Values.monitoredEnvironments.environments }}
      {{- $assets := list }}
      {{- range $asset := $env.assets }}
        {{- $rewritten := deepCopy $asset }}
        {{- $_ := set $rewritten "environment-id" $envId }}
        {{- if or (eq $asset.type "KUBERNETES_API") (eq $asset.type "tech.illuin.wombat-module.kubernetes-api") }}
          {{- $_ := set $rewritten "config-path" (printf "/kubeconfigs/%s.config" $asset.id) }}
        {{- end }}
        {{- $assets = append $assets $rewritten }}
      {{- end }}
      {{- $envObj := dict "id" ($env.id | default $envId) "assets" $assets }}
      {{- $_ := set $environments $envId $envObj }}
    {{- end }}
    {{- $output := dict "environments" $environments }}
    {{- toYaml $output | nindent 4 }}
