{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled (not .Values.ingress.basicAuth.existingSecret) .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wombat.fullname" . }}-basic-auth
  labels:
    {{- include "wombat.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ htpasswd .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password | b64enc | quote }}
{{- end }}
