{{- if and (eq .Values.persistence.type "SQLITE_WITH_BACKUP") .Values.persistence.backup.enabled (not .Values.persistence.backup.s3.existingSecret) .Values.persistence.backup.s3.accessKey .Values.persistence.backup.s3.secretKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wombat.fullname" . }}-s3-backup
  labels:
    {{- include "wombat.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.persistence.backup.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.persistence.backup.s3.secretKey | b64enc | quote }}
{{- end }}
