{{- if .Values.monitoredEnvironments.kubeconfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wombat.fullname" . }}-kubeconfigs
  labels:
    {{- include "wombat.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.monitoredEnvironments.kubeconfigs }}
  {{ printf "%s.config" .id }}: {{ .content | b64enc | quote }}
  {{- end }}
{{- end }}
